-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 12:59:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversation` (
  `idconversation` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconversation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messages` (
  `idmessages` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `time` INT NULL,
  `number_conseversation` INT NOT NULL,
  `sender` VARCHAR(45) NOT NULL,
  `receiver` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmessages`, `number_conseversation`),
  INDEX `fk_messages_conversation_idx` (`number_conseversation` ASC) VISIBLE,
  CONSTRAINT `fk_messages_conversation`
    FOREIGN KEY (`number_conseversation`)
    REFERENCES `conversation` (`idconversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_has_conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_has_conversation` (
  `user_idUser` INT NOT NULL,
  `conversation_idconversation` INT NOT NULL,
  PRIMARY KEY (`user_idUser`, `conversation_idconversation`),
  INDEX `fk_user_has_conversation_conversation1_idx` (`conversation_idconversation` ASC) VISIBLE,
  INDEX `fk_user_has_conversation_user1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_conversation_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_conversation_conversation1`
    FOREIGN KEY (`conversation_idconversation`)
    REFERENCES `conversation` (`idconversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
